USE xzjt9tep1d8f63ht;

CREATE TABLE IF NOT EXISTS specialties (
    ID int NOT NULL AUTO_INCREMENT,
    specialty varchar(255) NOT NULL,
    available boolean,
    PRIMARY KEY (ID)
);

INSERT INTO specialties (specialty, available) 
VALUES 
('Addiction psychiatrist',1), 
('Adolescent medicine specialist',1),
('Allergist',1),
('Anesthesiologist',1),
('Cardiac electrophysiologist',1),
('Cardiologist',1),
('Cardiovascular surgeon',1),
('Colon and rectal surgeon',1),
('Critical care medicine specialist',1),
('Dermatologist',1),
('Developmental pediatrician',1),
('Emergency medicine specialist',1),
('Endocrinologist',1),
('Family medicine physician',1),
('Forensic pathologist',1),
('Gastroenterologist',1),
('Geriatric medicine specialist',1),
('Gynecologist',1),
('Gynecologic oncologist',1),
('Hand surgeon',1),
('Hematologist',1),
('Hepatologist',1),
('Hospitalist',1),
('Hospice and palliative medicine specialist',1),
('Hyperbaric physician',1),
('Infectious disease specialist',1),
('Internist',1),
('Interventional cardiologist',1),
('Medical examiner',1),
('Medical geneticist',1),
('Neonatologist',1),
('Nephrologist',1),
('Neurological surgeon',1),
('Neurologist',1),
('Nuclear medicine specialist',1),
('Obstetrician',1),
('Occupational medicine specialist',1),
('Oncologist',1),
('Ophthalmologist',1),
('Oral surgeon (maxillofacial surgeon)',1),
('Orthopedic surgeon',1),
('Otolaryngologist (ear, nose, and throat specialist)',1),
('Pain management specialist',1),
('Pathologist',1),
('Pediatrician',1),
('Perinatologist',1),
('Physiatrist',1),
('Plastic surgeon',1),
('Psychiatrist',1),
('Pulmonologist',1),
('Radiation oncologist',1),
('Radiologist',1),
('Reproductive endocrinologist',1),
('Rheumatologist',1),
('Sleep disorders specialist',1),
('Spinal cord injury specialist',1),
('Sports medicine specialist',1),
('Surgeon',1),
('Thoracic surgeon',1),
('Urologist',1),
('Vascular surgeon',1)
;
